### ISSUE TITLE
I can not create LTSP image

### ISSUE THREAD

**Issue by isobelle2998** [ltsp/community#107]
I tried to create an image using a image with the .qcow2 extension.
The image runs well.
Primarly when I tried to run this command: 
`ln -rs home/ltsp-server/Téléchargements/lubuntu.qcow2 /srv/ltsp/lubuntu.img`, 
I was told that the directory `/srv/ltsp` does not exist. So I had to create ltsp in /srv myself
Then, when I run this command:
`ltsp image debian`
I get this error:
```
LTSP command failed: blkid -po export /srv/ltsp/lubuntu.img
Aborting ltsp
I don't know how to mount /srv/ltsp/lubuntu.img
```

**Comment by alkisg** [comment]
I transferred this issue to discussions (https://github.com/ltsp/community/issues) instead of bugs (https://github.com/ltsp/ltsp/issues).

**Comment by isobelle2998** [comment]
This is the output of the commands above:
```
root@ltspserver-Standard-PC-Q35-ICH9-2009:~# file -L /srv/ltsp/x86_32.img
/srv/ltsp/x86_32.img: cannot open `/srv/ltsp/x86_32.img' (No such file or directory)
root@ltspserver-Standard-PC-Q35-ICH9-2009:~# blkid -p /srv/ltsp/x86_32.img
blkid: erreur : /srv/ltsp/x86_32.img: Aucun fichier ou dossier de ce type
```

**Comment by alkisg** [comment]
You need to use YOUR file (/srv/ltsp/lubuntu.img), not my example (/srv/ltsp/x86_32.img).
E.g.

```shell
file -L /srv/ltsp/lubuntu.img
```

**Comment by isobelle2998** [comment]
Yes I am using virt-manager.
These are the outputs:
```
root@ltspserver-Standard-PC-Q35-ICH9-2009:~# file -L /srv/ltsp/lubuntu.img
/srv/ltsp/lubuntu.img: QEMU QCOW Image (v3), 8589934592 bytes
root@ltspserver-Standard-PC-Q35-ICH9-2009:~# blkid -p /srv/ltsp/lubuntu.img
root@ltspserver-Standard-PC-Q35-ICH9-2009:~#
```

**Comment by alkisg** [comment]
Right, so " QEMU QCOW Image" is the wrong format.
Delete that image, and create a new one, with format "raw", not "qcow2".

**Comment by isobelle2998** [comment]
I tried with the format "raw". And it worked fine. Thank you.
