### ISSUE TITLE
Multiple live iso-Images to choose from

### ISSUE THREAD

**Issue by feschoppe** [ltsp/community#109]
Hello everyone,
is there a way to deliver multiple live systems to netboot without ltsp mode?
I followed these steps to netboot one live iso:
https://github.com/ltsp/community/wiki/Non-LTSP-iPXE-entries
It works pretty fine, but I would like to netbook several different isos. What’s the best way to do that?

**Comment by alkisg** [comment]
Maybe https://netboot.xyz/ ?
