### ISSUE TITLE
Autologin not working on Ubuntu 20.04

### ISSUE THREAD

**Issue by Purpi** [ltsp/community#126]
Hello,

I have a problem with autologin. It doesn't work at all and I can't figure out why.

My System:
- KVM virtual machine
- Ubuntu 20.04

My ltsp.conf:
[yy:yy:yy:yy:yy:yy]
HOSTNAME=Gaestezimmer
AUTOLOGIN=kodi13
PASSWORDS_Gaestezimmer="kodi13/XXXXXXXXXX"
HOSTS_Gaestezimmer="192.168.10.7 mythserver"

The password is correctly passed and the last line is written to /etc/hosts. I don't know, why autologin isn't working.

I hope, someone can help.

Thanks
Marcus

**Comment by CarlosAPCunha** [comment]
Hi!

See -> https://github.com/ltsp/community/issues/118

**Comment by alkisg** [comment]
Also try this:

```shell
[yy:yy:yy:yy:yy:yy]
RELOGIN=0
```

There's a bug in lightdm which makes autologin not work in some cases, and it needs either a zero timeout, which then breaks re-login, or a long timeout, which can be adjusted with RELOGIN_TIMEOUT. This should be solved in lightdm, it can't be solved in LTSP.

**Comment by Purpi** [comment]
Thanks for your help!

In the meantime, I have found the solution: after I have recreated the image, the auto login also works.

So do I have to recreate the image after every change in ltsp.conf?

**Comment by alkisg** [comment]
No, after changing ltsp.conf you only need to run `ltsp initrd`.
