### ISSUE TITLE
root access on clients

### ISSUE THREAD

**Issue by Mogaba** [ltsp/community#136]
How do you get root privileges on clients (chroot image)? It seems LTSP does something with /etc/shadow file so you can't login with local root account.

**Comment by alkisg** [comment]
Read the following sections from the [ltsp.conf man page](https://ltsp.org/man/ltsp.conf/):

* PWMERGE_SUR=, PWMERGE_SGR=, PWMERGE_DGR=, PWMERGE_DUR=: these explain how the user account merging is performed.
* POST_INIT_SET_ROOT_HASH: this, in the examples section, shows one way to set a root password in ltsp.conf instead of in the image. That way, the root password will work for all images and you don't have to set one in the chroot or in the server.

**Comment by Mogaba** [comment]
I think I'm doing something wrong. Do I need to use PWMERGE_DUR for chroot accounts to appear in the client? Because this doesn't work:

[clients]
PWMERGE_DUR="user1"

I added user1 to the chroot image but there is no user1 in the shadow file in the client.

**Comment by alkisg** [comment]
First, did you run `ltsp initrd` to have the ltsp.conf change transferred to ltsp.img?
Second, are you sure you want "user1" to be a local user, unable to login via SSH?
Third, why didn't the POST_INIT_SET_ROOT_HASH work for your needs? What exactly are you trying to do, that users in ltsp.conf do not cover it?

**Comment by Mogaba** [comment]
Yes, I did `ltsp initrd`.
I'm just trying to understand how to add local users (and how to enable local root).
POST_INIT_SET_ROOT_HASH works, yes, but it seems a bit weird - editing shadow file manually. Is this the right way to add local users? And what exactly does PWMERGE_DUR do?

**Comment by alkisg** [comment]
Where does /home/username come from, for your "local user"? SSHFS, NFS, a local disk partition, or do you plan to include that in the squashfs image?

The normal place to put users in ltsp is in ltsp.img, not in the chroot; that way it will work with all images.

**Comment by Mogaba** [comment]
> The normal place to put users in ltsp is in ltsp.img, not in the chroot; that way it will work with all images

Sorry, I'm a bit confused, did I get this right: "ltsp image" removes chroot users (unless --cleanup=0), "ltsp initrd" makes ltsp.img that contains server's users, then users from both images merge together during boot?

**Comment by alkisg** [comment]
That is correct.
Note that there are no shadow entries in ltsp.img, so this isn't a security issue.
