### ISSUE TITLE
How to login with Windows domain accounts

### ISSUE THREAD

**Issue by Mogaba** [ltsp/community#139]
If LTSP server is a member of an Active Directory domain (joined using sssd), how do you login with domain accounts on the clients?

**Comment by MAccadia** [comment]
This question has been raised in https://github.com/ltsp/ltsp/issues/16. There is currently no clean documented way to do that.

See :
 *  https://github.com/ltsp/community/wiki/LTSP-and-Samba-Windows-NT-Domain
 * https://github.com/ltsp/ltsp/issues/16#issuecomment-588127315
