### ISSUE TITLE
support for screen scripts

### ISSUE THREAD

**Issue by wforumw** [ltsp/community#48]
Hi,
In the old LTSP5 we could use screen scripts (SCREEN_xx) each accessible by pressing the Ctrl-Alt-Fx
We used it to start remote desktop sessions.
Is this still possible or is there a better way to connect some clients to Windows Servers.?
Many thanks

**Comment by alkisg** [comment]
I think there's enough information in the wiki and in issues currently for LTSP users to be able to implement their own screen sessions. Moving this issue to community.

**Comment by jphein** [comment]
@alkisg Has this changed at all since you added SESSION_SCRIPT?
https://github.com/ltsp/ltsp/issues/18#issuecomment-550353273

I'm having trouble with the session showing up in the login menu. Let alone calling it automatically.
I'm using Ubuntu Bionic and Ubuntu 19.10.

**Comment by alkisg** [comment]
@jphein, I haven't committed SESSION_SCRIPT yet, so no changes there.

Open a terminal on the client and check your /usr/share/xsession scripts, if the session's there, it should show up in the DM screen.

**Comment by jphein** [comment]
It just autoboots a normal session for me. The session file is there now.

```
kiosk@ltsp103:/usr/share/xsessions$ ls
kodi.desktop  plasma.desktop  ubuntu.desktop  xfreerdp.desktop
kiosk@ltsp103:/usr/share/xsessions$ cat xfreerdp.desktop 
[Desktop Entry]
Name=XTERM
Comment=This session just runs an XTERM
Exec=xterm
TryExec=xterm
Icon=xterm
Type=Application
DesktopNames=XTERM
Keywords=launch;XTERM;desktop;session;
kiosk@ltsp103:/usr/share/xsessions$ 
```

I'll turn of autoboot and manually try to call the session file.

**Comment by jphein** [comment]
Manually selecting the XTERM session worked. 
So just the part of selecting the default session didn't work. 
Do we set that somewhere else in the ltsp.conf?

**Comment by jphein** [comment]
cat /etc/X11/default-display-manager
/usr/sbin/gdm3

**Comment by jphein** [comment]
sudo apt install lightdm
