### ISSUE TITLE
Regarding documentation hosting

### ISSUE THREAD

**Issue by alkisg** [ltsp/community#51]
This started as an issue to support Raspberry Pis, but then it changed its topic to documentation hosting, so another issue was opened for Raspberry Pis in https://github.com/ltsp/ltsp/issues/68.

**Comment by stevensantos-docs** [comment]
Alkis,

You have made it clear that my choosing to include the Ubuntu help documents in my efforts is not acceptable to you.  

I will finish what reorg I started on the Ubuntu help, but you have made it clear that documenting the new LTSP project is not a project that is worthwhile to me. 

Hopefully you will find someone else who will be willing to do the documentation.  

I wish you luck in your project.

**Comment by alkisg** [comment]
Steven you may do whatever you want in the UbuntuLTSP wiki; I just don't want to *personally* waste time on something that I feel will harm LTSP users.

But please do rename all those LTSP19 pages; the old name is "LTSP5" and the new is "LTSP"; writing LTSP19 there next year will be extremely confusing as the version then will be LTSP 20.
There's no point in putting the version number of a software in the URLs, except for LTSP5 which is obsolete and will never have a version change again.
