### ISSUE TITLE
Add support for netboot.xyz Enhancement Request

### ISSUE THREAD

**Issue by jphein** [ltsp/community#58]
Can we add netboot.xyz under ipxe more options? 
It works really well. Check here: https://github.com/ltsp/community/wiki/netboot.xyz-(ipxe-OS-installer)
Only problem is that my edits are reset everytime I run `ltsp ipxe`

**Comment by jphein** [comment]
Thanks @alkisg! I understand. 
Would the "custom ipxe entries" be added in ltsp.conf?
Like CUSTOM_IPXE_NETBOOTXYZ="chain --autofree https://boot.netboot.xyz" ?
I really like the idea, but don't NEED it at the moment.

**Comment by alkisg** [comment]
Right, something like that.

On the other hand, if ltsp.ipxe gets too many parameters and becomes too customizable, it won't be user-editable anymore, so there's a balance involved.
