### ISSUE TITLE
Local authentication support

### ISSUE THREAD

**Issue by kvaps** [ltsp/community#60]
Hi,
We need an option for disable ltsp pam authentication.
Some users uses sssd and other methods for authentication.

Optionally we also need to keep local accounts as well. 

I would like to add two new variables:

- `LOCAL_AUTH=<0|1>` - for enable or disable local authentication (default: 0)
- `CLEANUP_USERS=<0|1>` - for enable or disable ltsp users cleanup (default: 1)

**Comment by alkisg** [comment]
OK I moved this one to the community, to serve as a quick how-to, as the LTSP code changes that were required, were implemented as part of other issues.

Thanks!

**Comment by alkisg** [comment]
Try to switch to vt2 and login from there. Note the error messages, if any.

Additionally, check the client /etc/passwd and /etc/shadow. Do they correctly list local users? See the [end of the ltsp.conf man page](https://ltsp.org/man/ltsp.conf/) for an example on how to set the root password to be able to login as root in the client.

That said, what's the use case? Where will /home come from in your scenario? Is it NFS, SSHFS, a local partition, a RAM disk?

**Comment by nwrox** [comment]
> Try to switch to vt2 and login from there. Note the error messages, if any.
>
> Additionally, check the client /etc/passwd and /etc/shadow. Do they correctly list local users? See the [end of the ltsp.conf man page]
(https://ltsp.org/man/ltsp.conf/) for an example on how to set the root password to be able to login as root in the client.
> 
> That said, what's the use case? Where will /home come from in your scenario? Is it NFS, SSHFS, a local partition, a RAM disk?

I must try this again, in my use case, i need to provide a clean linux env (debian + openbox) for thinclients to connect in our citrix env through citrix workspace app, but this isn't working so far.
