### ISSUE TITLE
Sometimes boot hangs after GNOME Display Manager started

### ISSUE THREAD

**Issue by wforumw** [ltsp/community#61]
Hi,
With around 20% of the clients end the boot process after starting the GNOME Display Manager (see picture). No login screen is coming. After schwitching to a  Console, give username/password and run 

> $ startx

 we are logged in and have our Gnome environment.
We have several client and several users, but the issue happens only in around 20% of boot

![gnomeDM](https://user-images.githubusercontent.com/12762849/68384284-96ae2880-0157-11ea-86dc-b784c453e73a.jpeg)

**Comment by alkisg** [comment]
AFAIK this issue isn't related to the LTSP code; moving to the community.

**Comment by MAccadia** [comment]
I just had LigthDM not showing up with MATE. This was cause by a bad / slow connection. Having the server and clients on the same switch really helps.

**Comment by wforumw** [comment]
Thanks,
But we have Server and Clients on the same Gigabit Switch, with LigthDM we don't have the issue but with LigthDM the screensaver does not work properly

**Comment by wforumw** [comment]
I have deactivated Wayland for all clients as it causes many boot problems.
