### ISSUE TITLE
Disabling iPXE shell by default

### ISSUE THREAD

**Issue by MAccadia** [ltsp/community#69]
Currently, LTSP's default iPXE menu gives access to an iPXE shell. Although it's useful for debugging, I think this should be disabled by default for security reasons.

**Comment by alkisg** [comment]
Allowing an iPXE shell is similar to allowing a Grub shell, which AFAIK is the default in Linux distributions.

For that reason, I think both the shell and the config menus should be on by default, and security-sensitive installations can opt to hide them, similarly to what they'd do with Grub.

The following ltsp.conf parameters should allow you to hide them:

```shell
[server]
POST_IPXE_HIDE_CONFIG="sed '/--key c/d' -i /srv/tftp/ltsp/ltsp.ipxe"
POST_IPXE_HIDE_SHELL="sed '/--key s/d' -i /srv/tftp/ltsp/ltsp.ipxe"
```

**Comment by MAccadia** [comment]
> Allowing an iPXE shell is similar to allowing a Grub shell

Agreed. This is the default for desktops and servers alike and makes sense if the physical access to those is controlled / secure. Anyone with grub shell cant get a root access if there is no disk encryption.

However, I think LTSP is used in contexts where the physical access is not always well controlled (students in my case). Maybe we can add a _security_ section in the official documentation.

**Comment by alkisg** [comment]
> Anyone with grub shell cant get a root access if there is no disk encryption.

I assume you meant "can" there.

> Maybe we can add a security section in the official documentation.

Sounds great; I invite you to start a community wiki page about it and I can pull it or link to it from the official docs.

https://github.com/ltsp/community/wiki/security

**Comment by MAccadia** [comment]
Done :-)

**Comment by alkisg** [comment]
Thanks, I linked to it in the https://ltsp.org/docs/ page.

**Comment by enaut** [comment]
@MAccadia - I hope you don't mind my edits (mostly grammar): https://github.com/ltsp/community/wiki/security/_compare/75851c4db9ac639e4c6f7fcc2fa85572b10b4048...d8a01f6a00207c655a7a5de6b8e426d2b3e386c8

**Comment by MAccadia** [comment]
Not at all. That's what wiki are for ;-)
