### ISSUE TITLE
Consider using pixiecore for the network booting

### ISSUE THREAD

**Issue by kvaps** [ltsp/community#76]
There is an amazing project - [pixiecore](https://github.com/danderson/netboot/tree/master/pixiecore) which is providing simplicity and everything need for the network booting on server side. It includes:

- TFTP-server
- HTTP-server
- DHCP-proxy

It can simple be runing inside docker container, and it provides an API for the configuration, We're using LTSP and starting readonly LTSP-servers in Kubernetes using the similar logic, so I just came up with an idea to implement support for LTSP.

As new LTSP19 is more modular, we can implement this support via special command, eg: `ltsp pixiecore` command will generate tree of directories and static files, which can be used by pixiecore as API for the network booting:
https://github.com/danderson/netboot/blob/master/pixiecore/README.api.md

**Comment by alkisg** [comment]
Since this needs no immediate action in the LTSP code base, I've moved it to the community issues.

**Comment by kvaps** [comment]
I think it does not require any special actions from LTSP side.

I already provided an example in https://github.com/ltsp/community/issues/76#issuecomment-557526786

After implementing https://github.com/ltsp/ltsp/pull/90 it also could be simple used like:
```
pixiecore boot --dhcp-no-bind \
  /srv/tftp/ltsp/x86_64/vmlinuz \
  /srv/tftp/ltsp/x86_64/initrd.img \
  /srv/tftp/ltsp/ltsp.img \
  --cmdline='ip=dhcp ltsp.image={{ ID "srv/ltsp/images/x86_64.img" }} loop.max_part=9'
```
